[package]
name = "anki-bible-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
anyhow = "1.0"
tabled = "0.16"
clap = { version = "4.5", features = ["derive"] }
