[package]
name = "statsutils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.10"
rusqlite = { version = "0.37.0", features = ["bundled", "functions"] }
